on: push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install redis cli
        run: sudo apt-get update -y && sudo apt-get install redis-tools -y

      - name: Test redis
        run: redis-cli -h localhost -p 6379 ping

      - name: Show secret
        run: echo "Secret is ${{ secrets.TOKEN_SECRET }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # Add your deployment commands here
          # For example, you might use rsync, scp, or a cloud provider's CLI tool
          # Example: rsync -avz ./dist/